### ISSUE TITLE
Empty system info in effectiveConfig.yaml

### ISSUE THREAD

**Issue by JoseOrtega17** [aws-greengrass/aws-greengrass-fleet-provisioning-by-claim#12]
**Describe the bug**
When running the fleet provisioning command it creates the effective config but the system info its empty. This is the output error:
`aws_tls_ctx_options_init_client_mtls_from_path failed (aws_last_error: AWS_ERROR_FILE_INVALID_PATH(44), Invalid file path.) AWS_ERROR_FILE_INVALID_PATH(44)
 Device not configured to talk to AWS IoT cloud. FleetStatusService is offline. {errorMessage=[thingName cannot be empty, certificateFilePath cannot be empty, privateKeyPath cannot be empty, rootCaPath cannot be empty, iotDataEndpoint cannot be empty, iotCredEndpoint cannot be empty], serviceName=FleetStatusService, currentState=NEW}
`

**To Reproduce**
```
sudo -E java -Droot="/greengrass/v2" -Dlog.store=FILE \
  -jar ~/GreengrassInstaller/lib/Greengrass.jar \
  --aws-region us-east-1 \
  --trusted-plugin ~/GreengrassInstaller/aws.greengrass.FleetProvisioningByClaim.jar \
  --init-config ~/GreengrassInstaller/config.yaml \
  --component-default-user ggc_user:ggc_group \
  --setup-system-service true
```
**Expected behavior**
![image](https://user-images.githubusercontent.com/98169387/173094606-ed9d89d0-255e-4195-873f-8ccbb0343fcc.png)
**Actual behavior**
```
---
system:
  certificateFilePath: ""
  privateKeyPath: ""
  rootCaPath: ""
  rootpath: "/greengrass/v2"
  thingName: ""
services:
  aws.greengrass.FleetProvisioningByClaim:
    configuration:
      awsRegion: "us-east-1"
      claimCertificatePath: "/greengrass/v2/claim-certs/claim.pem.crt"
      claimCertificatePrivateKeyPath: "/greengrass/v2/claim-certs/claim.private.pem.key"
```

**Environment**
 - OS: [e.g. Ubuntu 18.04]
 - JDK version:
 - Nucleus version: "2.5.6"
 - AWS Fleet Provisioning plugin version:
